### ISSUE TITLE
ember-modifier v3.2.3+ crashes during build on parsing syntax (Missing semicolon)

### ISSUE THREAD

**Issue by IgnaceMaes** [ember-modifier/ember-modifier#464]
When upgrading addons that rely on `ember-modifier` versions 3.2.3 and above, the build phase of an Ember app crashes on the syntax in `modifier.ts`. It seems to be related to the changes introduced in the following MR https://github.com/ember-modifier/ember-modifier/pull/280.

When pinning the resolution of `ember-modifier` to v3.2.2 the issue doesn't occur.

What could be the cause of this issue? Could it be a peer dependency that's not up to date, or is there actually something wrong here?

**Details**

Environment:
- Ember v3.28.8
- Node.js v14.19.1

Running `ember serve` results in the following error:

```
ERROR Summary:

  - broccoliBuilderErrorStack: SyntaxError: <REDACTED>/ember-modifier/-private/function-based/modifier.ts: Missing semicolon (37:10)

  35 | // value from a `modifier()` call.
  36 | export type FunctionBasedModifier<S> =
> 37 |   abstract new () => FunctionBasedModifierInstance<S>;
     |           ^
  38 |
  39 | /**
  40 |  * The (optional) return type for a modifier which needs to perform some kind of
    at Object._raise (<REDACTED>/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:776:17)
    at Object.raiseWithData (<REDACTED>/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:769:17)
    at Object.raise (<REDACTED>/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:737:17)
    at Object.semicolon (<REDACTED>/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:9165:10)
    at Object.tsParseTypeAliasDeclaration (<REDACTED>/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:6176:10)
    at Object.tsParseDeclaration (<REDACTED>/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:6498:23)
    at Object.tsTryParseExportDeclaration (<REDACTED>/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:6403:17)
    at Object.parseExportDeclaration (<REDACTED>/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:6973:26)
    at Object.maybeParseExportDeclaration (<REDACTED>/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:12946:31)
    at Object.parseExport (<REDACTED>/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:12884:29)
  - code: [undefined]
  - codeFrame: <REDACTED>/ember-modifier/-private/function-based/modifier.ts: Missing semicolon (37:10)

  35 | // value from a `modifier()` call.
  36 | export type FunctionBasedModifier<S> =
> 37 |   abstract new () => FunctionBasedModifierInstance<S>;
     |           ^
  38 |
  39 | /**
  40 |  * The (optional) return type for a modifier which needs to perform some kind of
  - errorMessage: ember-modifier/-private/function-based/modifier.ts: <REDACTED>/ember-modifier/-private/function-based/modifier.ts: Missing semicolon (37:10)

  35 | // value from a `modifier()` call.
  36 | export type FunctionBasedModifier<S> =
> 37 |   abstract new () => FunctionBasedModifierInstance<S>;
     |           ^
  38 |
  39 | /**
  40 |  * The (optional) return type for a modifier which needs to perform some kind of
        in /var/folders/9h/5lcgcj596r94wnt0shgmjdjc0000gp/T/broccoli-281835QSMOpGE670Q/out-499-funnel
        at broccoli-persistent-filter:Babel > [Babel: ember-modifier] (Babel: ember-modifier)
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: ember-modifier/-private/function-based/modifier.ts
    - line: [undefined]
    - treeDir: /var/folders/9h/5lcgcj596r94wnt0shgmjdjc0000gp/T/broccoli-281835QSMOpGE670Q/out-499-funnel
  - message: ember-modifier/-private/function-based/modifier.ts: <REDACTED>/ember-modifier/-private/function-based/modifier.ts: Missing semicolon (37:10)

  35 | // value from a `modifier()` call.
  36 | export type FunctionBasedModifier<S> =
> 37 |   abstract new () => FunctionBasedModifierInstance<S>;
     |           ^
  38 |
  39 | /**
  40 |  * The (optional) return type for a modifier which needs to perform some kind of
        in /var/folders/9h/5lcgcj596r94wnt0shgmjdjc0000gp/T/broccoli-281835QSMOpGE670Q/out-499-funnel
        at broccoli-persistent-filter:Babel > [Babel: ember-modifier] (Babel: ember-modifier)
  - name: Error
  - nodeAnnotation: Babel: ember-modifier
  - nodeName: broccoli-persistent-filter:Babel > [Babel: ember-modifier]
  - originalErrorMessage: <REDACTED>/ember-modifier/-private/function-based/modifier.ts: Missing semicolon (37:10)

  35 | // value from a `modifier()` call.
  36 | export type FunctionBasedModifier<S> =
> 37 |   abstract new () => FunctionBasedModifierInstance<S>;
     |           ^
  38 |
  39 | /**
  40 |  * The (optional) return type for a modifier which needs to perform some kind of
  - stack: SyntaxError: <REDACTED>/ember-modifier/-private/function-based/modifier.ts: Missing semicolon (37:10)

  35 | // value from a `modifier()` call.
  36 | export type FunctionBasedModifier<S> =
> 37 |   abstract new () => FunctionBasedModifierInstance<S>;
     |           ^
  38 |
  39 | /**
  40 |  * The (optional) return type for a modifier which needs to perform some kind of
    at Object._raise (<REDACTED>/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:776:17)
    at Object.raiseWithData (<REDACTED>/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:769:17)
    at Object.raise (<REDACTED>/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:737:17)
    at Object.semicolon (<REDACTED>/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:9165:10)
    at Object.tsParseTypeAliasDeclaration (<REDACTED>/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:6176:10)
    at Object.tsParseDeclaration (<REDACTED>/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:6498:23)
    at Object.tsTryParseExportDeclaration (<REDACTED>/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:6403:17)
    at Object.parseExportDeclaration (<REDACTED>/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:6973:26)
    at Object.maybeParseExportDeclaration (<REDACTED>/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:12946:31)
    at Object.parseExport (<REDACTED>/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:12884:29)

=================================================================================

```

**Comment by SergeAstapov** [comment]
looks like it chokes on `abstract`, which TS version do you use?

**Comment by IgnaceMaes** [comment]
The app I'm working on doesn't use TypeScript at all. So it must come from a dependency?

Looking in the lockfile there are quite some `ember-cli-typescript` versions. Is there a minimum version that is required?

**Comment by nickschot** [comment]
Running into the same thing while upgrading an app. I'm only using ember-modifier indirectly through ember-in-viewport. No typescript in my own project.

**Comment by knownasilya** [comment]
Is this project only shipping ts? Was a build step forgotten during release?

**Comment by rtablada** [comment]
We've run into this as well. I'm able to use some force resolutions to use an older version of `ember-modifier`, but that's not an ongoing solution.

Having the assets prebuild before publish would be ideal if possible.

**Comment by knownasilya** [comment]
Ran into this again lol.

**Comment by chriskrycho** [comment]
Sorry, I missed this discussion. v3 of the addon uses the classic Ember CLI build mode, and classic Ember CLI builds for apps written in TS *all* ship uncompiled TS, just as v1 JS addons ship uncompiled JS. The solution is to make sure you have an appropriately recent version of ember-cli-babel, including if necessary its transitive dependencies on Babel’s core and plugins.

The good news is, when we ship v4 (very soon now!) it will be a modern/Embroider/v2 format addon, which will ship *lightly* compiled (to current spec) JS, with TS compiled out to type defs.

**Comment by yads** [comment]
What is an appropriately recent version of ember-cli-babel and @babel/core? I have @babel/core 7.20.2 and ember-cli-babel 7.26.11 and I'm still getting this error without pinning to 3.2.2.

**Comment by yads** [comment]
So what I ended up doing is de-duping @babel/core in my yarn.lock file, re-running yarn which got rid of a bunch of old versions of @babel/core. After doing that, my build started working.

**Comment by zion03** [comment]
Hey, everyone!
I had the same problem when I was updating my old application to the new node.
I resolved the biggest part of the problems but finally received

```  Build Error (broccoli-persistent-filter:Babel > [Babel: ember-modifier]) in ember-modifier/-private/function-based/modifier.ts

/home/front/ember-modifier/-private/function-based/modifier.ts: Unexpected token, expected ";" (37:11)

  35 | // value from a `modifier()` call.
  36 | export type FunctionBasedModifier<S> =
> 37 |   abstract new () => FunctionBasedModifierInstance<S>;
     |            ^
  38 | 
  39 | /**
  40 |  * The (optional) return type for a modifier which needs to perform some kind of

 ```
It's hard to debug because I even don't have this folder `ember-modifier`
I'll appreciate any thoughts or ideas

Working packages list on node 14.
```
{
  "name": "front",
  "version": "0.0.0",
  "private": true,
  "description": "Small description for front goes here",
  "license": "MIT",
  "author": "",
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "repository": "",
  "scripts": {
    "build": "ember build",
    "lint:js": "eslint ./*.js app config lib server tests",
    "start": "ember serve",
    "test": "ember test"
  },
  "devDependencies": {
    "@ember-intl/cp-validations": "^4.0.1",
    "@ember/jquery": "^1.1.0",
    "@ember/render-modifiers": "^1.0.2",
    "@fortawesome/ember-fontawesome": "^0.2.2",
    "@fortawesome/free-brands-svg-icons": "^5.13.0",
    "@fortawesome/free-solid-svg-icons": "^5.13.0",
    "babel-eslint": "^10.1.0",
    "bootstrap-sass": "^3.4.1",
    "broccoli-asset-rev": "^3.0.0",
    "ember-ajax": "^3.1.0",
    "ember-auto-import": "^1.6.0",
    "ember-bootstrap": "^2.8.1",
    "ember-cli": "^3.17.0",
    "ember-cli-app-version": "^3.2.0",
    "ember-cli-babel": "^7.19.0",
    "ember-cli-dependency-checker": "^3.2.0",
    "ember-cli-dotenv": "^2.2.3",
    "ember-cli-eslint": "^5.1.0",
    "ember-cli-fastboot": "^2.2.2",
    "ember-cli-htmlbars": "^4.3.1",
    "ember-cli-inject-live-reload": "^2.0.2",
    "ember-cli-moment-shim": "^3.8.0",
    "ember-cli-notifications": "^6.3.2",
    "ember-cli-one-script": "0.0.1",
    "ember-cli-qunit": "^4.4.0",
    "ember-cli-sass": "^7.2.0",
    "ember-cli-shims": "^1.2.0",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-uglify": "^3.0.0",
    "ember-cli-update": "^0.54.6",
    "ember-composable-helpers": "^4.0.0",
    "ember-cp-validations": "^4.0.0-beta.10",
    "ember-cropperjs": "^0.8.0",
    "ember-data": "^3.17.0",
    "ember-data-storefront": "^0.18.0",
    "ember-decorators": "^6.1.1",
    "ember-export-application-global": "^2.0.1",
    "ember-fetch": "^8.0.1",
    "ember-file-upload": "^2.7.1",
    "ember-infinity": "^1.4.9",
    "ember-intl": "^5.5.0",
    "ember-load-initializers": "^1.1.0",
    "ember-maybe-import-regenerator": "^0.1.6",
    "ember-modal-dialog": "^3.0.0-beta.4",
    "ember-moment": "^8.0.0",
    "ember-page-title": "^6.0.3",
    "ember-phoenix": "1.0.3",
    "ember-phone-input": "^5.2.1",
    "ember-power-select": "^4.1.0",
    "ember-resolver": "^8.0.0",
    "ember-route-action-helper": "^2.0.8",
    "ember-simple-auth": "^3.0.0",
    "ember-source": "^3.18.0",
    "ember-truth-helpers": "^2.1.0",
    "eslint-plugin-ember": "^8.14.0",
    "liquid-fire": "^0.31.0",
    "loader.js": "^4.7.0",
    "torii": "^0.10.1",
    "fastboot-app-server": "3.0.0"
  },
  "engines": {
    "node": "10.* || >= 12"
  },
  "dependencies": {
    "request": "^2.88.2"
  }
}
```

Updated (node 20 and 18 cause the same problem) with error above:
```
{
  "name": "front",
  "version": "0.0.0",
  "private": true,
  "description": "Small description for front goes here",
  "license": "MIT",
  "author": "",
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "repository": "",
  "scripts": {
    "build": "ember build",
    "lint:js": "eslint ./*.js app config lib server tests",
    "start": "ember serve",
    "test": "ember test"
  },
  "devDependencies": {
    "@ember-intl/cp-validations": "^6.0.0",
    "@ember/jquery": "^1.1.0",
    "@ember/render-modifiers": "^2.1.0",
    "@fortawesome/ember-fontawesome": "^2.0.0",
    "@fortawesome/free-brands-svg-icons": "^6.5.1",
    "@fortawesome/free-solid-svg-icons": "^6.5.1",
    "babel-eslint": "^10.1.0",
    "bootstrap-sass": "^3.4.1",
    "broccoli-asset-rev": "^3.0.0",
    "ember-ajax": "^5.1.2",
    "ember-auto-import": "^2.0.0",
    "ember-bootstrap": "^5.1.1",
    "bootstrap": "^5.3.2",
    "ember-cli": "^3.17.0",
    "ember-cli-app-version": "^3.2.0",
    "ember-cli-babel": "^8.1.0",
    "@babel/core":"^7.23.9",
    "ember-cli-dependency-checker": "^3.2.0",
    "ember-cli-dotenv": "^2.2.3",
    "ember-cli-eslint": "^5.1.0",
    "ember-cli-fastboot": "^2.2.2",
    "ember-cli-htmlbars": "^4.3.1",
    "ember-cli-inject-live-reload": "^2.0.2",
    "ember-cli-moment-shim": "^3.8.0",
    "ember-cli-notifications": "^9.0.0",
    "ember-cli-one-script": "0.0.1",
    "ember-qunit": "^8.0.2",
    "ember-cli-sass": "^11.0.1",
    "ember-cli-shims": "^1.2.0",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-uglify": "^3.0.0",
    "ember-cli-update": "^0.54.6",
    "ember-composable-helpers": "^4.0.0",
    "ember-cp-validations": "^6.0.0",
    "ember-cropperjs": "^0.8.0",
    "ember-data": "^3.17.0",
    "ember-data-storefront": "^0.18.0",
    "ember-decorators": "^6.1.1",
    "ember-export-application-global": "^2.0.1",
    "ember-fetch": "^8.0.1",
    "ember-file-upload": "^2.7.1",
    "ember-infinity": "^1.4.9",
    "ember-intl": "^5.7.2",
    "ember-load-initializers": "^1.1.0",
    "ember-maybe-import-regenerator": "^0.1.6",
    "ember-modal-dialog": "^3.0.0-beta.4",
    "ember-moment": "^8.0.0",
    "ember-page-title": "^6.0.3",
    "ember-phoenix": "1.0.3",
    "ember-phone-input": "^5.2.1",
    "ember-power-select": "^4.1.0",
    "ember-resolver": "^8.0.0",
    "ember-route-action-helper": "^2.0.8",
    "ember-simple-auth": "^3.0.0",
    "ember-source": "^3.18.0",
    "ember-truth-helpers": "^2.1.0",
    "eslint-plugin-ember": "^8.14.0",
    "liquid-fire": "^0.31.0",
    "loader.js": "^4.7.0",
    "torii": "^0.10.1",
    "fastboot-app-server": "3.0.0",
    "webpack": "^5.90.1"
  },
  "engines": {
    "node": "10.* || >= 12"
  },
  "dependencies": {
    "request": "^2.88.2"
  }
}
```

Thanks!

**Comment by yads** [comment]
See my comment above yours, you likely have an old version of @babel/core interfering.
