### ISSUE TITLE
Deprecation: Versions of modifier manager capabilities prior to 3.22 have been deprecated

### ISSUE THREAD

**Issue by Turbo87** [ember-modifier/ember-modifier#75]
After updating https://github.com/rust-lang/crates.io to Ember 3.26 I've started seeing deprecation warnings in the test suite:

> deprecate.js:136 DEPRECATION: Versions of modifier manager capabilities prior to 3.22 have been deprecated. You must update to the 3.22 capabilities. [deprecation id: manager-capabilities.modifiers-3-13] See https://emberjs.com/deprecations/v3.x#toc_manager-capabilities-modifiers-3-13 for more details.
        at logDeprecationStackTrace (http://localhost:4040/assets/vendor.js:35109:21)
        at HANDLERS.<computed> (http://localhost:4040/assets/vendor.js:35242:9)
        at raiseOnDeprecation (http://localhost:4040/assets/vendor.js:35136:9)
        at HANDLERS.<computed> (http://localhost:4040/assets/vendor.js:35242:9)
        at invoke (http://localhost:4040/assets/vendor.js:35254:9)
        at deprecate (http://localhost:4040/assets/vendor.js:35210:28)
        at Object.modifierCapabilities$1 [as _modifierManagerCapabilities] (http://localhost:4040/assets/vendor.js:10714:62)
        at new FunctionalModifierManager (http://localhost:4040/assets/vendor.js:111676:51)
        at Module.callback (http://localhost:4040/assets/vendor.js:111704:18)
>
> deprecate.js:136 DEPRECATION: Versions of modifier manager capabilities prior to 3.22 have been deprecated. You must update to the 3.22 capabilities. [deprecation id: manager-capabilities.modifiers-3-13] See https://emberjs.com/deprecations/v3.x#toc_manager-capabilities-modifiers-3-13 for more details.
        at logDeprecationStackTrace (http://localhost:4040/assets/vendor.js:35109:21)
        at HANDLERS.<computed> (http://localhost:4040/assets/vendor.js:35242:9)
        at raiseOnDeprecation (http://localhost:4040/assets/vendor.js:35136:9)
        at HANDLERS.<computed> (http://localhost:4040/assets/vendor.js:35242:9)
        at invoke (http://localhost:4040/assets/vendor.js:35254:9)
        at deprecate (http://localhost:4040/assets/vendor.js:35210:28)
        at Object.modifierCapabilities$1 [as _modifierManagerCapabilities] (http://localhost:4040/assets/vendor.js:10714:62)
        at new ClassBasedModifierManager (http://localhost:4040/assets/vendor.js:111499:51)
        at http://localhost:4040/assets/vendor.js:111642:38

It looks like these deprecation warnings are caused by the `ember-modifier` addon, which we are using in the latest version: 2.1.1

/cc @pzuraq @rwjblue

**Comment by nbibler** [comment]
Seeing the same deprecation after the Ember 3.26.1 upgrade (from Ember 3.25.3) in https://github.com/railsdiff/railsdiff.

**Comment by boris-petrov** [comment]
There is https://github.com/ember-modifier/ember-modifier/pull/63 but it's not being merged for some reason. :smile:
