### ISSUE TITLE
Cannot read properties of undefined (reading 'manager')

### ISSUE THREAD

**Issue by amk221** [ember-modifier/ember-modifier#851]
I have a conditional modifier like:

```hbs
<div
  class="dropdown"
  {{(if this.isOpen (modifier "position-dropdown"))}}
>
  {{yield}}
</div>
```

I have a method called `handleFocusOut`, which closes the dropdown when focus leaves the related interactive element.

When closed, I see:

```
runtime.js:3997 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'manager')
    at TransactionImpl.commit (runtime.js:3997:1)
    at EnvironmentImpl.commit (runtime.js:4062:1)
    at inTransaction (runtime.js:4082:1)
    at Renderer._renderRoots (index.js:4957:1)
    at Renderer._renderRootsTransaction (index.js:5001:1)
    at Renderer._revalidate (index.js:5033:1)
    at invoke (backburner.js:280:1)
    at Queue.flush (backburner.js:197:1)
    at DeferredActionQueues.flush (backburner.js:358:1)
    at Backburner._end (backburner.js:798:1)
commit @ runtime.js:3997
commit @ runtime.js:4062
inTransaction @ runtime.js:4082
_renderRoots @ index.js:4957
_renderRootsTransaction @ index.js:5001
_revalidate @ index.js:5033
invoke @ backburner.js:280
flush @ backburner.js:197
flush @ backburner.js:358
_end @ backburner.js:798
end @ backburner.js:589
_run @ backburner.js:842
_join @ backburner.js:819
join @ backburner.js:629
loopEnd @ index.js:4806
_trigger @ backburner.js:896
_end @ backburner.js:811
Backburner._boundAutorunEnd @ backburner.js:523
Promise.then (async)
iterations @ backburner.js:26
flush @ index.js:40
_scheduleAutorun @ backburner.js:964
_end @ backburner.js:804
Backburner._boundAutorunEnd @ backburner.js:523
Promise.then (async)
iterations @ backburner.js:26
flush @ index.js:40
_scheduleAutorun @ backburner.js:964
_end @ backburner.js:804
Backburner._boundAutorunEnd @ backburner.js:523
Promise.then (async)
iterations @ backburner.js:26
flush @ index.js:40
_scheduleAutorun @ backburner.js:964
_end @ backburner.js:804
Backburner._boundAutorunEnd @ backburner.js:523
Promise.then (async)
iterations @ backburner.js:26
flush @ index.js:40
_scheduleAutorun @ backburner.js:964
_end @ backburner.js:804
Backburner._boundAutorunEnd @ backburner.js:523
Promise.then (async)
iterations @ backburner.js:26
flush @ index.js:40
_scheduleAutorun @ backburner.js:964
_end @ backburner.js:804
Backburner._boundAutorunEnd @ backburner.js:523
Promise.then (async)
iterations @ backburner.js:26
flush @ index.js:40
_scheduleAutorun @ backburner.js:964
_ensureInstance @ backburner.js:955
scheduleOnce @ backburner.js:679
scheduleOnce @ index.js:185
handleFocusOut @ index.js:316
```

**Comment by amk221** [comment]
Error is now 

```
Cannot destructure property 'manager' of '.for' as it is undefined.
```

**Comment by amk221** [comment]
Here is a failing test

https://github.com/zestia/ember-select-box/commit/340e246bd61d49c26d896c139f6c3359506543bc

**Comment by amk221** [comment]
Raised on ember.js repo

https://github.com/emberjs/ember.js/issues/20708

**Comment by amk221** [comment]
I think there's something else going on here.

This issue has popped up again, but in a scenario where the above fix I mentioned doesn't work

```gjs
<div
  class="side-bar"
  {{(if
    @sortable (modifier  sortable onChange=@onChangeCardOrder)
  )}}
>
```

**Comment by NullVoxPopuli** [comment]
that's a different error -- can you open a new issue with repro? thanks! <3

**Comment by NullVoxPopuli** [comment]
that's also closed, and resolved by a comment saying it was naming clash?

can you repro in one file: https://limber.glimdown.com/ ?
